# Generated by Django 4.2 on 2023-06-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capitals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='countries',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='countries',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='countries',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
