# Generated by Django 4.2 on 2023-06-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capitals', '0002_countries_image_alter_countries_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='countries',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
